// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5M-bHkDGdvFcQvYykMtcoZk9zgpCRa64',
    appId: '1:870267699571:web:acf4818f92e2f08f154506',
    messagingSenderId: '870267699571',
    projectId: 'rememberme-9713c',
    authDomain: 'rememberme-9713c.firebaseapp.com',
    storageBucket: 'rememberme-9713c.appspot.com',
    measurementId: 'G-H70EE5Z97F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkSSp_NhD4-RPZem9Z9tUApx_ebG9iMw4',
    appId: '1:870267699571:android:75bbc129d9cf59a1154506',
    messagingSenderId: '870267699571',
    projectId: 'rememberme-9713c',
    storageBucket: 'rememberme-9713c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-rLQ6cQBAlqJmBzN1TYc-NuQzGKSuoA',
    appId: '1:870267699571:ios:f44995dee7641b6d154506',
    messagingSenderId: '870267699571',
    projectId: 'rememberme-9713c',
    storageBucket: 'rememberme-9713c.appspot.com',
    iosClientId: '870267699571-7pm78f0qrjfubtukq76nm1sbcdpd705n.apps.googleusercontent.com',
    iosBundleId: 'com.example.rememberme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-rLQ6cQBAlqJmBzN1TYc-NuQzGKSuoA',
    appId: '1:870267699571:ios:f44995dee7641b6d154506',
    messagingSenderId: '870267699571',
    projectId: 'rememberme-9713c',
    storageBucket: 'rememberme-9713c.appspot.com',
    iosClientId: '870267699571-7pm78f0qrjfubtukq76nm1sbcdpd705n.apps.googleusercontent.com',
    iosBundleId: 'com.example.rememberme',
  );
}
